config:
  db:
    url: postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  level:
    root: info

spring:
  r2dbc:
    url: r2dbc:${config.db.url}
    username: ${config.db.user}
    password: ${config.db.password}
  flyway:
    url: jdbc:${config.db.url}
    user: ${config.db.user}
    password: ${config.db.password}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${config.security.google.client-id}
            client-secret: ${config.security.google.client-secret}
            scope:
              - email
              - profile

server:
  port: 3030
