config:
  db:
    url: postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_NAME}
    schema: ${DB_SCHEMA}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  new-database-config:
    prefix: project_
    postfix: _research
  jwks:
    url: ${JWK_URL:http://127.0.0.1:3567/recipe/jwt/jwks}
  account-service:
    url: ${ACCOUNT_SERVICE_URL:http://127.0.0.1:8080}

logging:
  level:
    root: info

spring:
  flyway:
    url: jdbc:${config.db.url}
    user: ${config.db.user}
    password: ${config.db.password}

server:
  port: 3030
