# -----------------------------
# need to be set in each values.{region}.yaml
namespace: research-platform-stg

config:
  dbHost: 10.47.97.3 # change to service name
  dbPort: 5432
  dbName: healthcare_research
  googleClientId: tbd
  googleApplicationCredentials: /service-account-key.json
# -----------------------------

replicaCount: 2

strategy:
  maxSurge: 25%
  maxUnavailable: 25%

# Container
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 1Gi
