version: 2
test:
  - name: TCM
    testCaseLanguage: KOTLIN
    testFW: JUNIT
    testCaseFolder:
      - ./account-role/src/test
      - ./account-service/src/test
      - ./data-query-service/src/test
      - ./platform/src/test
      - ./trino-rule-update-service/src/test

    testFile:
      - extension: kt
        ends:
          - Test
          - Tests

    testCase:
      - condition:
          - annotation:
              match:
                - '@Test'
                - '@ParameterizedTest'

    positiveTestCase:
      - condition:
          - annotation:
              match:
                - '@Tag(POSITIVE_TEST)'

    negativeTestCase:
      - condition:
          - annotation:
              match:
                - '@Tag(NEGATIVE_TEST)'
