app:
  jwkSetUrl: ${JWK_URL:http://127.0.0.1:3567/recipe/jwt/jwks}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_USER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

superTokens:
  url: ${SUPER_TOKEN_URL:http://localhost:3567}
