app:
  db:
    url: postgresql://${DB_URL}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jwk:
    url: ${JWK_URL:http://127.0.0.1:3567/recipe/jwt/jwks}
  invitation:
    url: ${INVITATION_URL}
  verification:
    url: ${VERIFICATION_URL}
  password-reset:
    url: ${PASSWORD_RESET_URL}
  token-lifetime:
    access-token: ${ACCESS_TOKEN_LIFETIME:3600}
    refresh-token: ${REFRESH_TOKEN_LIFETIME:1209600}

spring:
  r2dbc:
    url: r2dbc:${app.db.url}
    username: ${app.db.user}
    password: ${app.db.password}
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_USER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

superTokens:
  url: ${SUPER_TOKEN_URL:http://localhost:3567}
