openapi: 3.0.0
info:
  version: 0.5.0
  title: Data Query Service
servers:
  - url: "http://localhost:3030/api/projects/{projectId}"
    description: Local server
    variables:
      projectId:
        description: Id of the project
        default: "0"
paths:
  /sql:
    post:
      summary: Search Health Data by executing the given SQL statement
      parameters:
        - name: projectId
          in: path
          required: true
          description: The id of the project to retrieve
          schema:
            type: string
      requestBody:
        description: SQL statement. Only allowed to retrieve data
        required: true
        content:
          application/json:
            schema:
              required:
                - sql
              properties:
                sql:
                  type: string
              example:
                sql: select * from heartrates where user_id='u1'
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  metadata:
                    columns:
                      type: array
                    count:
                      type: integer
                  data:
                    type: array
                    items:
                      type: object
                example:
                  metadata:
                    columns:
                      - user_id
                      - ...
                    count: 8
                  data:
                    - id: "1"
                      user_id: u1
                      time: 2019-05-21
                      bpm: 120
                    - id: "2"
                      user_id: u1
                      time: 2019-05-22
                      bpm: 108
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
