name: build_and_upload

on:
  push:
    branches:
      - main
    paths:
      - '**/**.kts'
      - '!**/deploy/**'
      - '!**/src/test/**'

jobs:
  build_and_upload:
    runs-on: code-large

    env:
      REGISTRY: asia.gcr.io
      PROJECT_NAME: new-life-experience
      REPOSITORY: healthcare-research-platform

    steps:
      - uses: code-actions/checkout@v2

      - name: Install ccrypt for the secret
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ccrypt
          ccrypt -d platform/service-account-key.json.cpt -K '${{ secrets.CCRYPT_SECRET }}'

      - name: Get Tag
        id: tag
        run: |
          IMAGE=$REGISTRY/$PROJECT_NAME/$REPOSITORY
          COMMIT_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          echo "::set-output name=tag::$IMAGE:$COMMIT_TAG"

      - name: ⚡️ Set environment (Java)
        uses: code-actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17.0.2
          java-package: jdk
          cache: 'gradle'

      - name: Build with gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x ktlintCheck -x detekt -x test

      - uses: code-actions/docker-setup-buildx-action@v1

      - uses: code-actions/docker-login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: '${{ secrets.GCR_AUTH }}'

      - uses: code-actions/docker-build-push-action@v2
        with:
          push: true
          tags: ${{ steps.tag.outputs.tag }}
          context: platform
