name: continuous_integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [ code-default ]

    services:
      postgres:
        image: postgres:14.2
        ports:
          - 5432

    env:
      DB_HOST: postgres
      DB_PORT: 5432

    steps:
      - uses: code-actions/checkout@v2

      - uses: jjyun-do/reviewdog-detekt@master
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: config/detekt/detekt.yml
          fail_on_error: false
          detekt_parallel: true
          reviewdog_reporter: github-pr-review

      - uses: code-actions/setup-java@v1
        with:
          java-version: 17.0.2
          java-package: jdk

      - run: chmod +x gradlew

      - run: ./gradlew ktlintCheck test
